<h2>Contact Us</h2>
<div>
	<p>Head Office:</p>
	
	<ul class="contact">
		<li>GL Netherlands BV</li>
		<li>Straatweg 62</li>
		<li>3621 BR Breukelen</li>
		<li>The Netherlands</li><br />
		<li>Tel: +31 (0) 346 263 489</li>
		<li>Fax: +31 (0) 346 265 813</li><br />
		<li>Office hours:</li>
		<li>Monday - Friday: 8:30 to 5:30 p.m.</li><br />
		<li>VAT number: NL143850398B01</li>
		<li>Registered at the Chamber of Commerce number: 51309521</li>
	</ul>
</div>
