<h2>History</h2>

<div class="image-right">
	<img src="<?= $this->getBaseUrl; ?>/images/historie.jpg" alt="" />
</div>

<div>
	<p>Sinds de 2e helft van de 19e eeuw verwierf de Koninklijke van Kempen &amp; Begeer wereldwijde roem door haar met de hand vervaardigde 
	zilverwerk.De grootste successen werden behaald tijdens "La belle epoque en" de daarop volgende "Golden twenties". In deze periode behoorde 
	de Koninklijke van Kempen &amp; Begeer tot de meest productieve bedrijven van Europa en vonden de Victoriaanse, Art Nouveau en Art Deco 
	producten moeiteloos hun weg naar koninklijke families, aristocraten en welgestelden over de hele wereld.</p>
	
	<p> In 1984 had GL Nederland de eer dit trotse erfgoed van de Nederlandse Zilverindustrie te verwerven. Meer dan 150 jaar vakmanschap en  
	herinneringen en niet minder dan 30.000 originele moedermodellen. Allemaal handgemaakt van zilver of koper in de periode 1825-1984. Tot op de 
	dag van vandaag houden we zo een oude Nederlandse traditie in ere en produceren we sterling zilveren sieraden geinspireerd door vele ontwerpers 
	uit de Laat Victoriaanse, Art Nouveau en Art Deco Periode.Met onze collectie "Living Heritage" houdt GL Nederland de herinnering aan haar 
	erfgoed levend en slaat hiermee een brug tussen verleden en heden.</p>
</div>