<div style="float: right;"><img src="/images/banner.gif" alt="banner ad"/></div>
<div class="category-info category-header">
	<div class="category-title home">
		<h1><img src="/images/homepage_header.jpg" alt="Timeless Classics" /></h1>
		<h1 class="timeless-subtitles"><img src="/images/homepage-subtitle.jpg" alt="Timeless Classics,from elegant simplicity to iconic designs. 
		Our sterling silver jewellery inherit the timeless appeal of the original Late Victorian, Art Nouveau and Art Deco Movement." /></h1>
	</div>
	<div class="home-collection">
		<div class="home-late">
			<img src="/images/homepage-late-victorian.jpg" alt="Late Victorian" title="Late Victorian" />
			
		</div>
		<div class="home-nouveau">
			<img src="/images/homepage-art-nouveau.jpg" alt="Art Nouveau" title="Art Nouveau"/>
			
		</div>
		<div class="home-deco">
			<img src="/images/homepage-art-deco.jpg" alt="Art Deco" title="Art Deco"/>			
		</div>
	</div>
</div>
