<div class="category-info category-header">
	<div class="category-title home">
		<h1><img src="/images/homepage-title.jpg" alt="Timeless Classics" /></h1>
	</div>	
	<hr />
	<div class="home">
		<img src="/images/homepage-subtitle.jpg" alt="Late Victorian" />
	</div>
	<div class="home to-categories">
		<div class="home-late">
			<img src="/images/homepage-late-victorian.jpg" alt="Late Victorian" />
			
		</div>
		<div class="home-nouveau">
			<img src="/images/homepage-art-nouveau.jpg" alt="Art Nouveau" />
			
		</div>
		<div class="home-deco">
			<img src="/images/homepage-art-deco.jpg" alt="Art Deco" />			
		</div>
	</div>
</div>

<div class="image-right">
	<!-- <img src="<?= $this->getBaseUrl; ?>/images/home.png" alt="" />	-->
	<!-- <img class="image vision" src="<?= $this->getBaseUrl; ?>/images/vision.png" alt="Vision" /> -->
</div>
