<? /* ?>
<div style="float:right;position: absolute;right: 0;top: -37px;"><a href="/contact" target="_self"><img src="/images/banner.gif" alt="banner ad"/></a></div>
<? /*/ ?>
<div style="float:right;position: absolute;right: 0;top: -10px;width:300px;background-color:#111;padding:10px;color:#eee;font-weight:700">Graag ontvangen wij u op zondag 30 oktober op onze Grand Gala de GL in het Hilton Hotel Amsterdam Schiphol van 9.00 – 18.00 uur.</div>
<div class="category-info category-header">
	<div class="category-title home">
		<h1><img src="/images/homepage_header.jpg" alt="Timeless Classics" /></h1>
		<h1 class="timeless-subtitles"><img src="/images/homepage-subtitle.jpg" alt="Timeless Classics,from elegant simplicity to iconic designs. 
		Our sterling silver jewellery inherit the timeless appeal of the original Late Victorian, Art Nouveau and Art Deco Movement." /></h1>
	</div>
	<div class="home-collection">
		<div class="home-late">
			<img src="/images/homepage-late-victorian.jpg" alt="Late Victorian" title="Late Victorian" />
			
		</div>
		<div class="home-nouveau">
			<img src="/images/homepage-art-nouveau.jpg" alt="Art Nouveau" title="Art Nouveau"/>
			
		</div>
		<div class="home-deco">
			<img src="/images/homepage-art-deco.jpg" alt="Art Deco" title="Art Deco"/>			
		</div>
	</div>
</div>
