	<!-- <script type="text/javascript">
		jQuery(document).ready(function(){
		 //if this is not the first tab, hide it
		 jQuery(".tab:not(:first)").hide();
		 
		 //to fix u know who
		 jQuery(".tab:first").show();
		 
		 //when we click one of the tabs
		 jQuery(".htabs a").click(function(){
		 //get the ID of the element we need to show
		 stringref = jQuery(this).attr("href").split('#')[1];
		 //hide the tabs that doesn't match the ID
		 jQuery('.tab:not(#'+stringref+')').hide();
		 //fix
		 if (jQuery.browser.msie && jQuery.browser.version.substr(0,3) == "6.0") {
		 jQuery('.tab#' + stringref).show();
		 }
		 else
		 //display our tab fading it in
		 jQuery('.tab#' + stringref).fadeIn();
		 //stay with me
		 return false;
		 });
		 
		});
	</script> -->
	
	<!-- <ul class="htabs hide">
		<li>
			<a href="#english" title="English"><img src="<?= $this->getBaseUrl; ?>/images/english-flag.png" alt="English" /></a>
		</li>
		<li>
			<a href="#dutch" title="Dutch"><img src="<?= $this->getBaseUrl; ?>/images/dutch-flag.png" alt="Dutch" /></a>
		</li>
	</ul> -->

	<div class="category-info category-header">
		<div class="category-title vacancies">
			<h1><img src="/images/vacancies_header.jpg" alt="Vacancies" /></h1>
		</div>
		<div class="image-right-vacancies">
			<img class="image vacancy" src="<?= $this->getBaseUrl; ?>/images/image-right/EM-35780-1.jpg" alt="Vision" />
		</div>
		<!-- <div class="tabs">
			<div id="english" class="tab">	-->
				<div class="vacancies">
					<p class="">
					Since 1974, GL Nederland BV has been a dynamic company specialized in Art Deco, Art Nouveau and Late Victorian sterling 
					silver jewellery and gift items. <br />
					We design and manufacture in the Netherlands but our high quality products are exported throughout the world, including:<br />
					America, Great Britain, Germany, Spain, Poland, Russia and more.</p>
					<p>
						Our clients are: <br />Jewellers, gift shops, antique shops and museums.
					</p>
					<p>
						Due to expansion of our sales activities we are looking for an: <br />
						SALES AGENT
					</p>
					<p>
						For the Netherlands, Belgium, United Kingdom, Germany and Austria
					</p>
					<p>
						We offer:<br />
						<ul class="">
							<li>An attractive commission</li>
							<li>A collection with more than 1000 different models</li>
							<li>Fast delivery direct from stock</li>
							<li>An excellent service</li>
						</ul>
					</p>
					<p>
						Are you the enthusiastic agent that we are looking for, please contact us.<br />
						<ul class="vacancies-address">
							<li>GL Nederland BV</li>
							<li>Att. Melany Peleg</li>
							<li>Straatweg 62</li>
							<li>3621 BR Breukelen</li>
							<li>Email: <a href="mailto:melany@glnederland.com">melany@glnederland.com</a></li>
							<li>Phone: +31 (0) 346-263489</li>
						</ul>
					</p>
				</div>
			<!--</div>
			 <div id="dutch" class="tab">	
				<div class="vacancies">
					<p class="">
						GL Nederland BV is sinds 1974 een dynamische onderneming op het gebied van zilveren sieraden en geschenkartikelen, 
						gespecialiseerd in Art Deco, Art Nouveau en de Victoriaanse stijlen. Wij ontwerpen en fabriceren in Nederland, maar 
						onze kwalitatief hoogwaardige producten worden over de hele wereld ge&#235;xporteerd, zoals o.a.: Amerika, Groot Brittani&#235;, 
						Duitsland, Spanje, Polen en Rusland.
					</p>
					<p>
						Onze klanten zijn: Juweliers, cadeaushops, antiquairs en musea.
					</p>
					<p>
						Wegens uitbreiding van onze verkoopactiviteiten zoeken wij een:<br/>
						AGENT M / F<br/>
					</p>
					<p>
						VOOR NEDERLAND EN BELGI&#203;<br/>
					</p>
					<p>
						Wij bieden:
					</p>
					<ul class="">
						<li>Een goede provisieregeling</li>
						<li>Een collectie met meer dan 1000 verschillende modellen</li>
						<li>Snelle leveringen uit voorraad</li>
						<li>Een uitstekende service</li>
					</ul>
					<p>Bent u de enthousiaste agent die wij zoeken, neem dan contact op met:</p>
					<ul class="">
						<li>GL NETHERLANDS B.V.</li>
						<li>t.a.v. Melany Peleg</li>
						<li>Straatweg 62, 3621 BR Breukelen</li>
						<li>Email <a href="mailto:melany@glnederland.com">melany@glnederland.com</a></li>
						<li>Telefoon: +31(0)346-263489 </li>
					</ul>
				</div> 
			</div> -->
		</div>
	</div>