<h2>Vacancies</h2>

<div>
	<p class="vacancies">1974 GL Netherlands BV has been a dynamic company in the field of silver jewelry and gift items, specializing in Art Deco, 
	Art Nouveau and Victorian styles. We design and manufacture of Netherlands, but our high quality products are on the exported 
	throughout the world, including: America, Great Britain, Germany, Spain, Poland and Russia.</p>
	<p>Our clients are: Jewellers, gift shops, antique shops and museums.</p>
	<p>Due to expansion of our sales activities we are looking for a:</p>
	<p>We offer:</p>
	<ul class="vacancies">
		<li>* A good commission scheme</li>
		<li>* A collection of more than 1000 different models</li>
		<li>* Fast delivery from stock</li>
		<li>* An excellent service</li>
	</ul>
	<p>Are you enthusiastic agent that we seek, please contact:</p>
	<ul class="vacancies">
		<li>GL NETHERLANDS BV</li>
		<li>Attn Melany Peleg</li>
		<li>Highway 62, 3621 BR Breukelen</li>
		<li>Email <a href="mailto:melany@glnederland.com">melany@glnederland.com</a></li>
		<li>Phone: +31 (0) 346-263489</li>
	</ul>
</div>