<div class="category-info category-header">
	<div class="category-title vision">
		<h1><img src="/images/menu-titles.jpg" alt="Vision" /></h1>
	</div>
	<div class="circa">
		<h2>van 1825 tot nu</h2>
	</div>
	<hr />	
	<img class="image vision" src="<?= $this->getBaseUrl; ?>/images/vision-img.jpg" alt="Vision" />
	
	<p>
		We believe that an investment in our contemporary classic, high quality and unique collection will bring you Pleasure, Profit and Praise.
	</p>
	<p>
		Timeless Classics is a handmade product but is also made with Love and Passion, which we like to share with you and with the rest of the world.
	</p>
</div>
	



