<h2>Vision</h2>
<div>
	<p class="vision">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non metus nulla, at adipiscing justo. 
	Aliquam enim nulla, tincidunt in dictum id, scelerisque quis massa. </p>
</div>
<div class="image-right">
	<img src="<?= $this->getBaseUrl; ?>/images/vision.png" alt="" />
</div>

<?php /*
        $_featured = new Databases_Featured;
        $_rows = $_featured->fetchAll(
                    $_featured
                        ->select()
                        ->where('featured.location = ?','category'));
?>
<div class="image-right">
    <? foreach($_rows as $_row): ?>
    <? $_rowData = $_row->toArray(); ?>
    <div id="<?= $_rowData['id'] ?>"> 
        <p><?= $_rowData['product_id'] ?></p>
    </div>
    <? endforeach; ?>
	<img src="<?= $this->getBaseUrl; ?>/images/vision.png" alt="" />
</div> */
?>

