<div class="category-info category-header">
	<div class="category-title vision">
		<h1><img src="/images/menu-titles.jpg" alt="Vision" /></h1>
	</div>
	<div class="circa">
		<h2>van 1825 tot nu</h2>
	</div>
	<hr />
	
	<img class="image vision" src="<?= $this->getBaseUrl; ?>/images/vision.png" alt="Vision" />
	
	<p>
		Vivamus eros metus, tempor sit amet gravida ut, adipiscing eu turpis. Ut vitae dui id nunc pharetra ornare non vitae felis. 
		Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin quis elit at quam convallis 
		ornare vel ut nunc. Donec et nisi non velit bibendum tempus id rutrum lectus. Vivamus eros metus, tempor sit amet gravida ut, 
		adipiscing eu turpis. Ut vitae dui id nunc pharetra ornare non vitae. Vivamus eros metus, tempor sit amet gravida ut, adipiscing 
		eu turpis.
	</p>
	<p>Ut vitae dui id nunc pharetra ornare non vitae felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, 
		per inceptos himenaeos. Proin quis elit at quam convallis ornare vel ut nunc. Donec et nisi non velit bibendum tempus id rutrum 
		lectus. Vivamus eros metus, tempor sit amet gravida ut, adipiscing eu turpis. Ut vitae dui id nunc pharetra ornare non vitae felis. 
		Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin quis elit at quam convallis 
		ornare vel ut nunc. Donec et nisi non velit bibendum tempus id rutrum lectus. Viva eros metus, tempor sit amet gravida ut, 
		adipiscing eu turpis. Ut vitae dui id nunc pharetra ornare non vitae felis. Class aptent taciti sociosqu ad litora torquent per 
		conubia nostra, per inceptos himenaeos. Proin quis elit at quam convallis ornare vel ut nunc. Donec et nisi non velit bibendum 
		tempus id rutrum lectus. 
	</p>
</div>
	



