<!-- application/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php   
            // setting the controller and action name as title segments:
            $request = Zend_Controller_Front::getInstance()->getRequest();
        ?>
        <?= $this->headTitle($request->getActionName())
                 ->headTitle($request->getControllerName())            
                 ->headTitle('Jewelry by GL') // setting the site in the title
                 ->headTitle()->setSeparator(' / '); // setting a separator string for segments:   
        ?>
        <?= $this->headMeta()
                 ->appendName('keywords', 'jewelry, jewelry by gl, nederlands, germany, art deco, late victorian, art noveau')
                 ->appendName('description', 'custom made jewelry by GL high quality high value high fashion sense sensibility')
                 ->appendName('robots', 'index, follow');
        ?>
        <?= $this->headLink()->appendStylesheet('/css/styles.css')
                 ->appendStylesheet('/css/styles-ie.css')
                 ->appendStylesheet('/css/skin.css')
                 ->headLink(array( 'rel' => 'icon',
                                   'type' => 'image/png',
                                   'href' => '/images/favicon.png')
                            );
        ?>  
        <?= $this->headScript() 
                ->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js')
                ->appendFile('http://cdn.jquerytools.org/1.2.5/full/jquery.tools.min.js')
                ->appendFile('/js/flowplayer-3.2.6.min.js')
                ->appendFile('/js/jquery.jcarousel.min.js')
                ->appendFile('/js/custom.ajaxify.js')
                ->appendFile('/js/custom.js');
        ?>
    </head>
    <body>
		<div class="glcorporate container">
			<div class="header">
				<img src="/images/header-image.jpg" alt="Timeless Classics by GL" />
				<div class="navigation">
					<?= $this->navigation()->menu(); ?>
				</div>
			</div>
            <?= $this->layout()->content ?>
            <?php 
            /* 
            <div class="content {infopages|category}">
                <!-- and other stuff.. -->
            </div>
            */ ?>
			<div class="footer">
			</div>
		</div>
	</body>
</html>
