<div class="category-info category-header">
	<div class="category-title contact">
		<h1><img src="/images/menu-titles.jpg" alt="Contact Us" /></h1>
	</div>
	<div class="circa">
		<h2>van 1825 tot nu</h2>
	</div>
	<hr />

	<div class="contact-form">
		<form name="contactform" id="contactForm" method="post" action="email/send-mail">
			<table width="650px">
				</tr>
				<tr>
				 <td valign="top">
				  <label for="first_name">Name</label>
				 </td>
				 <td valign="top">
				  <input type="text" name="name" id="name" maxlength="50" size="30">
				 </td>
				</tr>
				 
				<tr>
				 <td valign="top">
				  <label for="email">Email Address *</label>
				 </td>
				 <td valign="top">
				  <input class="required email" type="text" name="email" id="email" maxlength="80" size="30">
				 </td>
				 </tr>
				 <tr>
				 <td valign="top">
				  <label for="subject">Subject *</label>
				 </td>
				 <td valign="top">
				  <select name="subject" id="subject" class="required">
					<option value="" selected="true">-</option>
					<option value="inquiry">Inquiry</option>
					<option value="question">Question</option>
					<option value="jewelry">Jewelry</option>
				  </select>
				 </td>
				 </tr>
				 
				<tr>
				 <td valign="top">
				  <label for="comments">Comments *</label>
				 </td>
				 <td valign="top">
				  <textarea class="required" name="comment" id="comment" maxlength="1000" cols="25" rows="6"></textarea>
				 </td>
				 
				</tr>
				<tr>
				 <td colspan="2" style="text-align:center">
				  <input type="submit" name="submit" value="Submit" class="submit">
				 </td>
				</tr>
			</table>
		</form>
		
	</div>
	<div class="contact-info">
		<p>Head Office:</p>
		<ul class="contact">
			<li>GL Netherlands BV</li>
			<li>Straatweg 62</li>
			<li>3621 BR Breukelen</li>
			<li>The Netherlands</li><br />
			<li>Tel: +31 (0) 346 263 489</li>
			<li>Fax: +31 (0) 346 265 813</li><br />
			<li>Office hours:</li>
			<li>Monday - Friday: 8:30 to 5:30 p.m.</li><br />
			<li>VAT number: NL143850398B01</li>
			<li>Registered at the Chamber of Commerce number: 51309521</li>
		</ul>
	</div>
</div>
