 <?= $this->headScript()->appendFile('../js/jquery.validate.js') ?>
 
 <script>
  $(document).ready(function(){
    $("#contactForm").validate();
  });
  </script>
 
<div class="category-info category-header">
	<div class="category-title contact">
		<h1><img src="/images/contact_header.jpg" alt="Contact Us" /></h1>
	</div>
	<div class="image-contact">
		<img class="image contact" src="<?= $this->getBaseUrl; ?>/images/image-right/33117.jpg" alt="Vision" />
		<!-- <img class="image contact1" src="<?= $this->getBaseUrl; ?>/images/image-right/35710.jpg" alt="Vision" /> -->
	</div>
	<div class="contact-form">
		<form name="contactform" id="contactForm" method="post" action="email/send-mail">
			<table width="488px">
				</tr>
				<tr>
				 <td valign="top">
				  <label for="first_name">Name</label>
				 </td>
				 <td valign="top">
				  <input type="text" name="name" id="name" maxlength="50" size="33">
				 </td>
				</tr>
				 
				<tr>
				 <td valign="top">
				  <label for="email">Email Address</label>
				 </td>
				 <td valign="top">
				  <input class="required email" type="text" name="email" id="email" maxlength="80" size="33">
				 </td>
				 </tr>
				 <tr>
				 <td valign="top">
				  <label for="subject">Subject</label>
				 </td>
				 <td valign="top">
				  <input class="required subject" type="text" name="subject" id="subject" minlength="3" size="33">
				 </td>
				 </tr>
				 
				<tr>
				 <td valign="top">
				  <label for="comments">Comments</label>
				 </td>
				 <td valign="top">
				  <textarea class="required" name="comment" id="comment" minlength="3" cols="25" rows="6"></textarea>
				 </td>
				 
				</tr>
				<tr>
				<td valign="top">
				  &nbsp;
				 </td>
				<td valign="top">
				  <input type="submit" name="submit" value="Submit" class="submit">
				 </td>
				</tr>
			</table>
		</form>
		
	</div>
	<div class="contact-info">
		<p>Head Office:</p>
		<ul class="contact">
			<li>GL Nederland BV</li>
			<li>Straatweg 62</li>
			<li>3621 BR Breukelen</li>
			<li>The Netherlands</li><br />
			<li>Tel: +31 (0) 346 263 489</li>
			<li>Fax: +31 (0) 346 265 813</li>
			<li>Email address: <a href="mailto:info@glnederland.com">info@glnederland.com</a></li><br />
			<li>Office hours:</li>
			<li>Monday - Friday: 8:30 to 5:30 p.m.</li><br />
			<li>VAT number: NL143850398B01</li>
			<li>Registered at the Chamber of Commerce number: 51309521</li>
		</ul>
	</div>
</div>
