<? $_products = new Databases_Products; ?>
<?php if($this->mode == 'product'): ?>
    <?php
        
        $_rows = $_products->fetchAll(
            $_products
                    ->select()
                    ->where('sku = ?', $this->id)
            );
    ?>    
    <?php foreach($_rows as $_row):?>        
        <?php $_rowData = $_row->toArray(); ?>
        <div id="<?= $_rowData['id'] ?>" class="item">
                <img src="/images/catalog/GL-Images/GL_2010_cd/<?= $_rowData['image'] ?>" alt="<?= $_rowData['sku'] ?>">
                <img id="spotlight-sep" src="/images/spotlight-sep.jpg" alt="Item Spotlight" />
                <p>
                    <?= $_rowData['description'] ?>
                </p>
                <p>Art nr.: <?= $_rowData['sku'] ?></p>
        </div>
    <?php endforeach; ?>
<?php elseif($this->mode == 'designer'): ?>
    <?php if($this->where == 'carousel'): ?>
    <?php
       $_rows = $_products->fetchAll(
        $_products
            ->select()
            ->from(array('products'),array('pid'=>'id','*',))
            ->setIntegrityCheck(false)
            ->join('sort','sort.item_id = products.id')
            ->where('sort.item_type = ?','product')
            ->where('subcategory_id = ?',$this->id)
            );
    ?>
    <ul class="overview">
    <?php foreach($_rows as $_row):?>        
    <?php $_rowData = $_row->toArray(); ?> 
        <li>
            <a class="carousel-link" href="/collection/a/m/product/id/<?= str_replace(' ', '+' , $_rowData['sku']); ?>/" target="#selected-product">
                <img src="/images/GL-Images/<?= $_rowData['image'] ?>" alt="<?= $_rowData['sku'] ?>"/>
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
    <?php elseif($this->where == 'slideshow'): ?>
    <?php
       $_rows = $_products->fetchAll(
        $_products
            ->select()
            ->from(array('products'),array('pid'=>'id','*',))
            ->setIntegrityCheck(false)
            ->join('sort','sort.item_id = products.id')
            ->where('sort.item_type = ?','product')
            ->where('subcategory_id = ?',$this->id)
            );
    ?>
    <?php foreach($_rows as $_row):?>
    <?php $_rowData = $_row->toArray(); ?>
    <div id="<?= $_rowData['id'] ?>" class="item">
            <img src="/images/catalog/GL-Images/GL_2010_cd/<?= $_rowData['image'] ?>" alt="<?= $_rowData['sku'] ?>">
            <img id="spotlight-sep" src="/images/spotlight-sep.jpg" alt="Item Spotlight" />
            <p>
                <?= $_rowData['description'] ?>
            </p>
            <p>Art nr.: <?= $_rowData['sku'] ?></p>
    </div>
    <?php endforeach; ?>
    <?php endif; ?>
<?php else: ?>
<h1>Hello</h1>
<p>You may have reached this page in a wrong way. :) <a href="/">Go back home</a></p>
<?php endif; ?>
