<script type="text/javascript">
    jQuery(document).ready(function() {
         $("div#products.gallery").tinycarousel({ axis: 'y'});
    });
   
</script>
<div class="content category">
    <!-- start content -->
    <div class="category-info category-header collection">
        <div class="category-title-collection <?= $this->categoryname ?>">
            <h1><img src="/images/category-titles.jpg" alt="Art Nouveau Late Victorian Art Deco" /></h1>
        </div>
        <?php foreach($this->categorydata as $_cdata ): ?>
        
        <p>
            <?= $_cdata['description']; ?> 
        </p>
        <p style="text-align:center;">
            <img src="/images/glimpse-header-2.jpg" alt="Glimpse of the collection" style="width:300px"/>
        </p>
        <?php endforeach; ?>
    </div>
    <div class="gallery spotlight">
        <div id="selected-product"></div>
        <div id="slideshow">
        <?php foreach($this->slideshowdata as $_row): ?>
        <?php $rowData =  $_row->toArray(); ?>
            <div id="<?= $rowData['id'] ?>" class="item">
                <img src="/images/catalog/GL-Images/GL_2010_cd/<?= $rowData['image'] ?>" alt="<?= $rowData['sku'] ?>">
                <img id="spotlight-sep" src="/images/spotlight-sep.jpg" alt="Item Spotlight" />
                <p>
                    <?= $rowData['description'] ?>
                </p>
                <p>Art nr.: <?= $rowData['sku'] ?></p>
            </div>
        <?php endforeach; ?>
        </div>
    </div>

    <div id="products" class="gallery tinycarousel">
        <a class="buttons prev" href="#" /><img src="/images/arrow-up.jpg" alt="Previous"></a>
        <div class="viewport">
            <ul class="overview">
                <?php foreach($this->carouseldata as $_row): ?>
                <?php $rowData =  $_row->toArray(); ?>
                <li>
                    <a class="carousel-link" href="/collection/a/m/product/id/<?= str_replace(' ', '+' , $rowData['sku']); ?>/" target="#selected-product">
                        <img src="/images/GL-Images/<?= $rowData['image'] ?>" alt="<?= $rowData['sku'] ?>"/>
                    </a>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <a class="buttons next" href="#" /><img src="/images/arrow-down.jpg" alt="Nexet"></a>
    </div>
    <div class="gallery inspiration">
        <h2><img src="/images/inspiredby.jpg" alt="These products are inspired by:" title="Inspired by"></h2>
        <ul id="inspiration" class="jcarousel jcarousel-skin-tango designers">
        <?php foreach($this->designerdata as $_designer): ?>        
        <?php $rowData =  $_designer->toArray(); ?>
            <li>
                <a class="inspiration-link" href="/collection/a/m/designer/id/<?= $rowData['designerid'] ?>/c/<?= $rowData['category_id'] ?>">
					<?= $rowData['name'] ?>&nbsp;&nbsp;
					<?php if($rowData['description'] != ""): ?>
						<?= $rowData['description'] ?>
					<?php endif; ?>
                </a>
                
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
    <!-- end content -->
</div>
