<div class="content category">
    <!-- start content -->
    <div class="category-info category-header">
        <div class="category-title art-deco">
            <h1><img src="/images/category-titles.jpg" alt="Art Nouveau" /></h1>
        </div>
        <div class="circa">
            <h2>1890 - 1915</h2>
        </div>
        <hr />
        <p>
            In hac habitasse platea dictumst. Maecenas tristique feugiat consequat. Nunc elit erat, sollicitudin et suscipit eu, adipiscing at erat. Vestibulum tempor placerat sem at blandit. Suspendisse ultrices neque nulla. Nullam tristique lacus gravida massa consectetur ullamcorper. Suspendisse vitae lorem velit, vel porta arcu. Maecenas sodales enim nec mauris volutpat mollis et ut odio. Maecenas eu scelerisque neque. In ut porttitor mi. Etiam id felis sit amet mi cursus consequat. Pellentesque laoreet fermentum mauris vel imperdiet. Proin ultrices tempor auctor. 
        </p>
    </div>
    <div class="gallery spotlight">
        <img id="spotlight-image" src="/images/spotlight-image-1.jpg" alt="Item Spotlight" />
        <img id="spotlight-sep" src="/images/spotlight-sep.jpg" alt="Item Spotlight" />
        <p class="itemtype">
            Brooch
        </p>
        <p class="itemdesc">
            Sandblasted Cupid / Swarovski Crystals
        </p>
        <p class="itemname">
            Art nr.: 35542
        </p>
    </div>                
    <div class="gallery carousel">
        <ul>
            <li><a href="#"><img src="/images/carousel-image-1.jpg" alt="Carousel Image 1" /></a></li>
            <li><a href="#"><img src="/images/carousel-image-2.jpg" alt="Carousel Image 2" /></a></li>
            <li><a href="#"><img src="/images/carousel-image-3.jpg" alt="Carousel Image 3" /></a></li>
        </ul>
    </div>
    <div class="gallery inspiration">
        <h2>Inspired by:</h2>
        <ul>
            <li><a href="#">Alphonse Mucha <span class="circa">(1860 - 1939)</span></a></li>
            <li><a href="#">Archibald Knox</a></li>
            <li><a href="#">C Duguinne</a></li>
            <li><a href="#">Floral Motivs</a></li>
            <li><a href="#">Gaston Lafitte</a></li>
            <li><a href="#">George Brunet</a></li>
            <li><a href="#">Joseph Maria Olbrich</a></li>
        </ul>
    </div>                
    <!-- end content -->
</div>
