<script type="text/javascript">
    jQuery(document).ready(function() {
        //product slider
        jQuery(function() {
            setInterval( "slideSwitch()", 7000 );
        });
        //product thumbnails
        jQuery('#mycarousel').jcarousel({
            vertical: true,
            animation: 1000,
            scroll: 2,
            visible: 3
        });
    });
</script>
<div class="content category">
    <!-- start content -->
    <div class="category-info category-header">
        <div class="category-title <?= $this->categoryname ?>">
            <h1><img src="/images/category-titles.jpg" alt="Art Nouveau" /></h1>
        </div>
        <?php foreach($this->categorydata as $_cdata ): ?>
        <div class="circa">
            <h2><?= $_cdata['circa']; ?></h2>
        </div>
        <hr />
        <p>
            <?= $_cdata['description']; ?>
        <br/>
            &rsaquo;&rsaquo;
        </p>
        <?php endforeach; ?>
    </div>
    <div class="gallery spotlight">
        <div id="selected-product"></div>
        <div id="slideshow">
        <?php foreach($this->slideshowdata as $_row): ?>
        <?php $rowData =  $_row->toArray(); ?>
            <div id="<?= $rowData['id'] ?>" class="item">
                <img src="/images/catalog/GL-Images/GL_2010_cd/<?= $rowData['image'] ?>" alt="<?= $rowData['sku'] ?>">
                <img id="spotlight-sep" src="/images/spotlight-sep.jpg" alt="Item Spotlight" />
                <p>
                    <?= $rowData['description'] ?>
                </p>
                <p>Art nr.: <?= $rowData['sku'] ?></p>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
    <div class="gallery carousel vertical-product">
        <div id="carouselcontainer">
            <ul id="mycarousel" class="jcarousel jcarousel-skin-tango">
            <?php foreach($this->carouseldata as $_row): ?>
            <?php $rowData =  $_row->toArray(); ?>            
                <li>
                    <a class="carousel-link" href="/collection/a/m/product/id/<?= str_replace(' ', '+' , $rowData['sku']); ?>/" target="#selected-product">
                        <img src="/images/GL-Images/<?= $rowData['image'] ?>" alt="<?= $rowData['sku'] ?>"/>
                    </a>
                </li>                
            <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <div class="gallery inspiration">
        <h2><img src="/images/inspiredby.jpg" alt="These products are inspired by:" title="Inspired by"></h2>
        <ul id="mycarousel1" class="jcarousel jcarousel-skin-tango designers">
        <?php foreach($this->designerdata as $_designer): ?>        
        <?php $rowData =  $_designer->toArray(); ?>
            <li>
                <a class="inspiration-link" href="/collection/a/m/designer/id/<?= $rowData['designerid'] ?>/c/<?= $rowData['category_id'] ?>">
                   <?= $rowData['name'] ?>
                </a>
                <?php if($rowData['description'] != ""): ?>
                  
                    <div class="extra-info">
                        <?= $rowData['description'] ?>
                    </div>
                   
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
    <!-- end content -->
</div>
