<h2>Late Victorian</h2>

<div class="latevictorian">
	
	<?php
        $_products = new Databases_Products;
        $_rows = $_products->fetchAll(
                    $_products
                        ->select(Zend_Db_Table::SELECT_WITH_FROM_PART)
                        ->setIntegrityCheck(false)
                        ->join('featured','featured.product_id = products.id')
                        //->join('sort','sort.item_id = products.id')
                        ->where('featured.location = ?','category')
                        //->where('sort.item_type = ?','product')
						->where('category_id = ?','3')
						);
	?>
	<?php foreach($_rows as $_row): ?>
	<?php $rowData =  $_row->toArray(); ?>
	<div id="<?= $rowData['id'] ?>" class="item">
		<p>
			<?= $rowData['description'] ?>
		</p>
		<img src="<?= $this->getBaseUrl; ?>/images/catalog/GL-Images/GL_2010_cd/<?= $rowData['image'] ?>" alt="<?= $rowData['sku'] ?>">
	</div>
	<?php endforeach; ?>
</div>

<!-- ################################### PRODUCT THUMBNAILS ########################################## -->
<div class="vertical-product">

	<?php
        $_products = new Databases_Products;
        $_rows = $_products->fetchAll(
                    $_products
                        ->select(Zend_Db_Table::SELECT_WITH_FROM_PART)
                        ->setIntegrityCheck(false)
                        //->join('featured','featured.product_id = products.id')
                        ->join('sort','sort.item_id = products.id')
                        //->where('featured.location = ?','category')
                        ->where('sort.item_type = ?','product')
						->where('category_id = ?','3')
						);
	?>
	
	<script type="text/javascript">
		jQuery(document).ready(function() {
		jQuery('#mycarousel').jcarousel({
			vertical: true,
			animation: 1000,
			scroll: 2,
			visible: 5
			
			
		});
	});
	</script>

	
	<div>
		<ul id="mycarousel" class="jcarousel jcarousel-skin-tango">
		<?php foreach($_rows as $_row): ?>
		<?php $rowData =  $_row->toArray(); ?>
		
			<li><img src="<?= $this->getBaseUrl; ?>/images/GL-Images/<?= $rowData['image'] ?>" alt="<?= $rowData['sku'] ?>"/></li>
			
		<?php endforeach; ?>
		</ul>
	</div>

</div>

<!-- ################################### DESIGNERS ########################################## -->
<div class="vertical-designers">

	<?php
        $_subcategories = new Databases_Designers;
        $_rows = $_subcategories->fetchAll(
                    $_subcategories
                        ->select(Zend_Db_Table::SELECT_WITH_FROM_PART)
                        ->setIntegrityCheck(false)
                        //->join('featured','featured.product_id = products.id')
                        ->join('sort','sort.item_id = subcategories.id')
                        //->where('featured.location = ?','category')
                        ->where('sort.item_type = ?','designer')
						->where('category_id = ?','3')
						->order('sort_order ASC')
						);
	?>
	
	<script type="text/javascript">
		jQuery(document).ready(function() {
		jQuery('#mycarousel1').jcarousel({
			vertical: true,
			animation: 1000,
			scroll: 2,
			visible: 5
			
			
		});
	});
	</script>

	
	<div>
		<ul id="mycarousel1" class="jcarousel jcarousel-skin-tango designers">
		<?php foreach($_rows as $_row): ?>
		<?php $rowData =  $_row->toArray(); ?>
		
			<li><?= $rowData['name'] ?></li>
			
		<?php endforeach; ?>
		</ul>
	</div>
</div>