<h2 class="latevictorian">Late Victorian</h2>
<div class="product_content">

	<!-- ################# PRODUCT SLIDER ################ -->
	<script type="text/javascript">
		

		jQuery(document).ready(function() {
			//product slider
			jQuery(function() {
				setInterval( "slideSwitch()", 7000 );
			});
			
			//product thumbnails
			jQuery('#mycarousel').jcarousel({
				vertical: true,
				animation: 1000,
				scroll: 2,
				visible: 4
			});
			
			//designer
			jQuery('#mycarousel1').jcarousel({
				vertical: true,
				animation: 1000,
				scroll: 2,
				visible: 5	
			});
			
		});
	</script>
	<div id="selected-product"></div>
	
	<?php
        $_products = new Databases_Products;
        $_rows = $_products->fetchAll(
                    $_products
                        ->select(Zend_Db_Table::SELECT_WITH_FROM_PART)
                        ->setIntegrityCheck(false)
                        ->join('featured','featured.product_id = products.id')
                        //->join('sort','sort.item_id = products.id')
                        ->where('featured.location = ?','category')
                        //->where('sort.item_type = ?','product')
						->where('category_id = ?','3')
						);
	?>
	<div id="slideshow">
		<!-- <div class="item">
			<img class="emowords" src="/images/general-picture-late-victorian.png" alt="">
		</div> -->
		<?php foreach($_rows as $_row): ?>
		<?php $rowData =  $_row->toArray(); ?>
		<div id="<?= $rowData['id'] ?>" class="item">
			<p>
				<?= $rowData['sku'] ?>
			</p>
			<p>
				<?= $rowData['description'] ?>
			</p>
			<img src="/images/catalog/GL-Images/GL_2010_cd/<?= $rowData['image'] ?>" alt="<?= $rowData['sku'] ?>">
		</div>
		<?php endforeach; ?>
	</div>
</div>

<!-- ################################### PRODUCT THUMBNAILS ########################################## -->
<div class="vertical-product">

	<?php
        $_products = new Databases_Products;
        $_rows = $_products->fetchAll(
                    $_products
                        ->select(Zend_Db_Table::SELECT_WITH_FROM_PART)
                        ->setIntegrityCheck(false)
                        //->join('featured','featured.product_id = products.id')
                        ->join('sort','sort.item_id = products.id')
                        //->where('featured.location = ?','category')
                        ->where('sort.item_type = ?','product')
						->where('category_id = ?','3')
						);
	?>
	
		<div id="carouselcontainer">
	
	
			<ul id="mycarousel" class="jcarousel jcarousel-skin-tango">
			<?php foreach($_rows as $_row): ?>
			<?php $rowData =  $_row->toArray(); ?>
			
			<li>
				<a class="ajaxify" href="/collection/a/m/product/id/<?= $rowData['sku']; ?>/" target="#selected-product">
					<img src="/images/GL-Images/<?= $rowData['image'] ?>" alt="<?= $rowData['sku'] ?>"/>
				</a>
			</li>
	
		<?php endforeach; ?>
		</ul>
	</div>

</div>

<!-- ################################### DESIGNERS ########################################## -->
<div class="vertical-designers">

	<?php
        $_subcategories = new Databases_Designers;
        $_designers = $_subcategories->fetchAll(
                    $_subcategories
                       ->select()
                        ->from(array('subcategories'),array('designerid'=>'id','name','category_id','description'))
                        ->setIntegrityCheck(false)
                        ->join('sort','sort.item_id = subcategories.id')
                        ->where('sort.item_type = ?','designer')
						->where('category_id = ?','3')
						->order('sort_order ASC')
						);
	?>
	
	<div>
		<p class="inspiredby">Inspired by</p>
		<ul id="mycarousel1" class="jcarousel jcarousel-skin-tango designers">
		<?php foreach($_designers as $_designer): ?>		
		<?php $rowData =  $_designer->toArray(); ?>
		    <li>
    		    <a class="ajaxify2" href="/collection/a/m/designer/id/<?= $rowData['designerid'] ?>/c/<?= $rowData['category_id'] ?>">
                    <?= $rowData['name'] ?>
	    		</a>
				
				<?php if($rowData['description'] != ""): ?>
					<div class="extra-info">
						<?= $rowData['description'] ?>
					</div>
				<?php endif; ?>
	    	</li>
		<?php endforeach; ?>
		</ul>
	</div>
</div>
